import { ItemModel } from '../../model/item.model';

export const ITEMS: ItemModel[] = [
  { id: 0, sku: '00', deleted: true, name: 'ERROR', description: 'bla', price:-1, picture: '', category: 'Euro' },
  { id: 1, sku: '11', deleted: false, name: 'Nocilla', description: 'bla', price:1, picture: 'http://images.math.cnrs.fr/IMG/png/section8-image.png', category: 'Euro' },
  { id: 2, sku: '12', deleted: false, name: 'Nutella', description: 'bla', price:12, picture: '', category: 'Euro' },
  { id: 3, sku: '13', deleted: false, name: 'Chocolate', description: 'bla', price:31,  picture: '', category: 'Euro' },
  { id: 4, sku: '14', deleted: false, name: 'Bombones', description: 'bla', price:14, picture: '', category: 'Euro' },
  { id: 5, sku: '15', deleted: false, name: 'Chocogalleta', description: 'bla', price:2, picture: '', category: 'Euro' },
  { id: 6, sku: '16', deleted: false, name: 'Turrón', description: 'bla', price:10, picture: '', category: 'Euro' },
  { id: 7, sku: '17', deleted: false, name: 'Cookies', description: 'bla', price:4, picture: '', category: 'Euro' },
  { id: 8, sku: '00', deleted: true, name: 'ERROR', description: 'bla', price:-1, picture: '', category: 'Euro' },
  { id: 9, sku: '11', deleted: false, name: 'Nocilla', description: 'bla', price:451, picture: 'http://images.math.cnrs.fr/IMG/png/section8-image.png', category: 'Euro' },
  { id: 10, sku: '12', deleted: false, name: 'Nutella', description: 'bla', price:16, picture: '', category: 'Euro' },
  { id: 11, sku: '13', deleted: false, name: 'Chocolate', description: 'bla', price:11, picture: '', category: 'Euro' },
  { id: 12, sku: '14', deleted: false, name: 'Bombones', description: 'bla', price:11, picture: '', category: 'Euro' },
  { id: 13, sku: '15', deleted: false, name: 'Chocogalleta', description: 'bla', price:51, picture: '', category: 'Euro' },
  { id: 14, sku: '16', deleted: false, name: 'Turrón', description: 'bla', price:17, picture: '', category: 'Euro' },
  { id: 15, sku: '00', deleted: true, name: 'ERROR', description: 'bla', price:-1, picture: '', category: 'Euro' },
  { id: 16, sku: '11', deleted: false, name: 'Nocilla', description: 'bla', price:1, picture: 'http://images.math.cnrs.fr/IMG/png/section8-image.png', category: 'Euro' },
  { id: 17, sku: '12', deleted: false, name: 'Nutella', description: 'bla', price:1, picture: '', category: 'Euro' },
  { id: 18, sku: '13', deleted: false, name: 'Chocolate', description: 'bla', price:1, picture: '', category: 'Euro' },
  { id: 19, sku: '14', deleted: false, name: 'Bombones', description: 'bla', price:1, picture: '', category: 'Euro' },
  { id: 20, sku: '15', deleted: false, name: 'Chocogalleta', description: 'bla', price:1, picture: '', category: 'Euro' },
  { id: 21, sku: '16', deleted: false, name: 'Turrón', description: 'bla', price:1, picture: '', category: 'Euro' },
];